name: imaginarynet
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.16
  - pip=20.3
  - cudatoolkit
  - cudnn
  - pytorch=1.11.0
  - torchvision=0.12.0
  - numpy>=1.20
  - pip:
    - wget
    - invisible-watermark
    - albumentations==0.4.3
    - diffusers
    - opencv-python==4.7.0.68
    - opencv-python-headless==4.7.0.68
    - pudb==2019.2
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - pytorch-lightning==1.4.2
    - omegaconf==2.1.1
    - test-tube>=0.7.5
    - streamlit>=0.73.1
    - einops==0.3.0
    - torch-fidelity==0.3.0
    - transformers==4.25.1
    - torchmetrics==0.6.0
    - kornia==0.6
    - taming-transformers-rom1504
    - git+https://github.com/patil-suraj/vqgan-jax.git
    - git+https://github.com/borisdayma/dalle-mini.git
    - git+https://github.com/openai/CLIP.git
    - -e stable-diffusion